### ISSUE TITLE
[BE] Soft Delete 기능 추가하기

### ISSUE THREAD

**Issue by jaeseongDev** [woowacourse-teams/2021-darass#133]

**Comment by jujubebat** [comment]
Soft Delete 기능이 무엇인가요??

**Comment by jaeseongDev** [comment]
실제 서비스를 운영할 때 데이터를 지우는 요청이 들어왔을 때, DB의 데이터를 실제로 지우면 여러가지 불편함이 생기는걸로 알고 있습니다. (ex. 회원 탈퇴 후 복구) 이 때문에, 데이터를 지우는 요청이 왔을 때 DB의 데이터를 삭제하지 않고, deletedAt과 같은 컬럼을 추가해서 지웠다는 표시만 해주는 형태의 DELETE를 의미합니다.

**Comment by jujubebat** [comment]
오오.. 저는 들어보기만 했는데, 도입하는거 정말 좋은거 같아요 👍
