### ISSUE TITLE
[BE] private 파일 모듈화

### ISSUE THREAD

**Issue by Sehwan-Jang** [woowacourse-teams/2021-darass#3]
.

**Comment by pjy1368** [comment]
## 서브 모듈 등록 방법
1. 설정 파일을 올릴 private 저장소를 만든다. (우리의 경우 https://github.com/jaeseongDev/darass-private-key)
2. ``git submodule add [자신의 private 저장소] ./src/main/resources/config`` 명령어를 통해 서브 모듈을 등록한다. 이 명령어를 통해 자동으로 config 디렉토리가 우리 프로젝트에서 생성되면서 private 저장소의 master 브랜치에 있는 설정 파일을 자동으로 가져오게 된다.
3. 2번 과정을 거치면 자동으로 .gitmodules파일이 생기는데, 해당 속성 맨 밑에 'branch = develop'을 추가하면 master 브랜치가 아니라 develop 브랜치에 있는 설정 파일을 가져올 수 있다.
4. 이후 ``git submodule update --remote`` 명령어를 입력하면 기존 master 브랜치에 있던 속성 파일이 develop 브랜치에 있던 속성 파일로 바뀐다. 마치 ``git checkout develop``와 유사한 효과라고 보면 된다.
5. 서브모듈이 등록된 프로젝트를 클론할 때는 단순히 ``git clone``가 아니라 ``git clone --recurse-submodules [자신의 프로젝트 저장소]``를 입력해야 한다.
6. 서브모듈에 있던 설정 정보를 업데이트할 때는 아래 명령어를 사용한다.
```
git submodule foreach git pull origin main

git submodule foreach git add .

git submodule foreach git commit -m "commit message"

git submodule foreach git push origin main
```
