### ISSUE TITLE
[FE][공통] Sentry ErrorBoundary를 사용하지 않고 직접 error를 sentry로 보내서 에러 위치 쉽게 파악하게 만들기

### ISSUE THREAD

**Issue by yungo1846** [woowacourse-teams/2021-darass#468]
센트리 에러바운더리를 사용하면 번들된 결과물의 코드 위치만을 알려줘서 에러가 어디서 발생했는지 확인하기가 어려움.

따라서 센트리 웹팩 플러그인을 사용하여 소스맵을 통해 해당 에러가 어디서 발생했는지 알아야함. 이를 위해서는 센트리 에러바운더리를 사용하면 안 됨.

**Comment by zereight** [comment]
보류
