### ISSUE TITLE
[BE] 테스트 코드 DisplayName Convention 관련 논의 

### ISSUE THREAD

**Issue by jujubebat** [woowacourse-teams/2021-darass#48]
```java
@DisplayName("Calculator 클래스")
public class Calculator {
    
    @DisplayName("sum 메서드는 합을 리턴한다.")
    @Test
    void sum(){
        
    }

    @DisplayName("minus 메서드는 차를 리턴한다.")
    @Test
    void minus(){

    }

    @DisplayName("multiply 메서드는 값이 0이라면 예외를 던진다.")
    @Test
    void multiply(){

    }
    
}
````

위와 같은 식의 테스트 코드 DisplayName 컨밴션은 어떠신가요?
아래 기술블로그 글을 참고했는데, 가독성이 좋다고 생각했습니다.

- [https://helloworld.kurly.com/blog/try-bdd/](https://helloworld.kurly.com/blog/try-bdd/)
- [https://johngrib.github.io/wiki/junit5-nested/](https://johngrib.github.io/wiki/junit5-nested/)

**Comment by jaeseongDev** [comment]
오오 깔끔하고 보기 좋을 것 같아요! 한 번 도입해보는 것도 좋은 것 같애요!!👍👍👍

**Comment by jaeseongDev** [comment]
단위 테스트에서는 위와 같이 하면 좋다고 생각하는데, 인수 테스트 같은 경우는 DisplayName 컨벤션을 어떻게 가져가면 될까요 ?

**Comment by jujubebat** [comment]
어떤 테스트에 위 컨밴션을 적용할지 얘기를 안했었군요! 음. . 인수테스트는 우리가 이전에 했던 방식대로 하는게 좋을 것 같습니다. 그 방식이 유저 시나리오를 파악하는데, 가독성이 좋다고 느껴졌습니다.
