### ISSUE TITLE
이슈 제목 컨밴션 변경을 고려한다. 

### ISSUE THREAD

**Issue by jujubebat** [woowacourse-teams/2021-darass#560]
현재 프론트, 백 엔드 이슈를 Label로 구분하고 있으니, 이슈 제목 앞에 `[FE]`, `[BE]`를 붙이는 컨밴션은 없애도 될 것 같습니다.

**Comment by jujubebat** [comment]
main, develop 커밋 내역을 보며 다시 생각해보니 원래대로 [FE], [BE] 붙이는게 좋을 것 같습니다.

**Comment by zereight** [comment]
이 이슈 언제있었지.. 모르고 [FE] 붙이고 있었네
