### ISSUE TITLE
squash and merge 제목 컨밴션을 정한다. 

### ISSUE THREAD

**Issue by jujubebat** [woowacourse-teams/2021-darass#609]
# 문제상황
![image](https://user-images.githubusercontent.com/37281119/135030431-897c79b6-98ad-4d85-8e3a-6d5932e5806f.png)
- PR에 포함된 커밋이 1개 일경우 위와같이 squash and merge 제목이 자동 생성된다.
<img width="562" alt="스크린샷 2021-09-28 오후 2 49 58" src="https://user-images.githubusercontent.com/37281119/135030757-11a33932-021e-42ff-88f8-7dd0fe9f8fe0.png">

- 커밋 제목들이 일관적이지 않다.

# 해결방법
- squash and merge 제목은 다음과 같이 한다.
  - 이슈 제목 (#이슈 번호)

**Comment by zereight** [comment]
번호를 붙이라는거져?

**Comment by jujubebat** [comment]
> 이슈제목 + 번호를 붙이라는거져?
> 커밋로그 + 번호는 안되구

넵 일관적으로 보이게 하려고 생각한건데 어떠신가요?

**Comment by zereight** [comment]
좋아연~~
