### ISSUE TITLE
[BE] 비밀 댓글 기능을 구현한다.

### ISSUE THREAD

**Issue by pjy1368** [woowacourse-teams/2021-darass#630]
### 비밀 댓글 체크 박스
![image](https://user-images.githubusercontent.com/56083021/136307635-fe0f319c-d59f-4cc3-9942-37252dfd7715.png)

### 작성자 또는 관리자가 아닌 일반 사용자가 비밀 댓글을 볼 때
![image](https://user-images.githubusercontent.com/56083021/136307718-765bc016-1586-420d-806e-b6fcc041dc73.png)

### 작성자 또는 관리자가 비밀 댓글을 볼 때
![image](https://user-images.githubusercontent.com/56083021/136307896-39487563-b204-4d52-ac13-6e031b2f3efb.png)

### 관리자가 댓글 관리창에서 비밀 댓글을 볼 때
![image](https://user-images.githubusercontent.com/56083021/136307867-2a80c5bb-c4ae-4314-9668-059f1f90afd8.png)

## 백엔드 구현 사항
- 댓글 컬럼으로 isSecret(이름 변경 가능) 추가.
- 작성자 또는 관리자가 아닌 일반 **로그인** 사용자가 일반 **로그인** 사용자의 비밀 댓글을 볼 때는 해당 댓글 작성자의 이름을 공백으로, 댓글의 내용을 "비밀 댓글입니다."라고 반환하기
- 작성자 또는 관리자가 아닌 일반 **로그인** 사용자가 일반 **비로그인** 사용자의 비밀 댓글을 볼 때는 해당 댓글의 내용만 "비밀 댓글입니다."라고 반환하기
- 작성자 또는 관리자가 아닌 일반 **비로그인** 사용자가 일반 **로그인** 사용자의 비밀 댓글을 볼 때는 해당 댓글 작성자의 이름을 공백으로, 댓글의 내용을 "비밀 댓글입니다."라고 반환하기
- 작성자 또는 관리자가 아닌 일반 **비로그인** 사용자가 일반 **비로그인** 사용자의 비밀 댓글을 볼 때는 해당 댓글 작성자의 이름을 공백으로, 댓글의 내용을 "비밀 댓글입니다."라고 반환하기
- 작성자 또는 관리자가 아닌 일반 **비로그인** 사용자가 비밀 댓글을 볼 때는 올바른 비밀 번호를 입력해야 조회가 가능하다.
  - 아래와 같이 일반 **비로그인** 사용자가 비밀 댓글을 달고, 관리자가 답글을 비밀 댓글로 다는 경우가 있을 수 있다.
  - 그럴 때는 최초로 일반 **비로그인** 사용자가 작성한 댓글의 비밀번호를 체크하는 로직을 만들고, 그 로직이 통과가 된다면 답글의 비밀 댓글도 볼 수 있다.
![image](https://user-images.githubusercontent.com/56083021/136324908-d4b4d796-681a-44a3-84e6-64aa1f8712c1.png)

## 프론트 구현 사항
- 댓글 컬럼의 isSecret(이름 변경 가능)이 true면 댓글 관리 페이지의 해당 댓글에 대해 비밀 댓글 표시해 준다.
- 댓글 컬럼의 isSecret(이름 변경 가능)이 true면 해당 댓글에 대해 비밀 댓글 표시해 준다. (단순히 백엔드에서 댓글의 내용을 "비밀 댓글입니다."라고 하는 것도 좋지만, 추가로 자물쇠 아이콘을 달아주면 더욱 가시성이 좋을 듯하다.)
- 댓글에 비밀 댓글 체크 박스를 생성한다. (꼭 체크 박스일 필요는 없고, 어떤 방식이든 비밀 댓글 기능 선택이 가능하면 됨.)

## 백엔드 구현 사항 가시성 있게 정리
================
<응답 모델 변환 시>
비밀 댓글의 작성자가 비로그인
-> 닉네임 노출, 내용 숨김

비밀 댓글의 작성자가 로그인
-> 닉네임, 내용 모두 숨김

================
<다라쓰 사용자 관점>
사용자가 비로그인 유저
-> 모든 비밀 댓글은 가려져 있고, 비밀 댓글의 비밀 번호를 올바르게 입력해야 내용을 볼 수 있음.
-> 로그인 유저의 비밀 댓글을 보기 위한 비밀 번호 입력할 권한 자체가 없음.

사용자가 로그인 유저 
-> 자기가 쓴 비밀 댓글 외에 모든 비밀 댓글은 가려져 있음.
-> 남의 비밀 댓글 보기 위한 비밀 번호 입력할 권한 자체가 없음.

사용자가 관리자
-> 모든 댓글 열람 가능.

**Comment by jaeseongDev** [comment]
전체저긍로 구성 좋은 것 같습니다!

> 작성자 또는 관리자가 아닌 일반 비로그인 사용자가 비밀 댓글을 볼 때는 올바른 비밀 번호를 입력해야 조회가 가능하다.

이 부분에서 비로그인 사용자가 자신의 댓글을 못알아보는 상황에 대해서는 어떻게 하는 것이 좋을까요 ?

**Comment by pjy1368** [comment]
> ## UI - 아래는 예시일 뿐, 다라쓰에 맞춰서 커스터마이징할 것.
> ### 비밀 댓글 체크 박스
> ![image](https://user-images.githubusercontent.com/56083021/136307635-fe0f319c-d59f-4cc3-9942-37252dfd7715.png)
> 
> ### 작성자 또는 관리자가 아닌 일반 사용자가 비밀 댓글을 볼 때
> ![image](https://user-images.githubusercontent.com/56083021/136307718-765bc016-1586-420d-806e-b6fcc041dc73.png)
> 
> ### 작성자 또는 관리자가 비밀 댓글을 볼 때
> ![image](https://user-images.githubusercontent.com/56083021/136307896-39487563-b204-4d52-ac13-6e031b2f3efb.png)
> 
> ### 관리자가 댓글 관리창에서 비밀 댓글을 볼 때
> ![image](https://user-images.githubusercontent.com/56083021/136307867-2a80c5bb-c4ae-4314-9668-059f1f90afd8.png)
> 
> ## 백엔드 구현 사항
> * 댓글 컬럼으로 isSecret(이름 변경 가능) 추가.
> * 작성자 또는 관리자가 아닌 일반 **로그인** 사용자가 일반 **로그인** 사용자의 비밀 댓글을 볼 때는 해당 댓글 작성자의 이름을 공백으로, 댓글의 내용을 "비밀 댓글입니다."라고 반환하기
> * 작성자 또는 관리자가 아닌 일반 **로그인** 사용자가 일반 **비로그인** 사용자의 비밀 댓글을 볼 때는 해당 댓글의 내용만 "비밀 댓글입니다."라고 반환하기
> * 작성자 또는 관리자가 아닌 일반 **비로그인** 사용자가 일반 **로그인** 사용자의 비밀 댓글을 볼 때는 해당 댓글 작성자의 이름을 공백으로, 댓글의 내용을 "비밀 댓글입니다."라고 반환하기
> * 작성자 또는 관리자가 아닌 일반 **비로그인** 사용자가 일반 **비로그인** 사용자의 비밀 댓글을 볼 때는 해당 댓글 작성자의 이름을 공백으로, 댓글의 내용을 "비밀 댓글입니다."라고 반환하기
> * 작성자 또는 관리자가 아닌 일반 **비로그인** 사용자가 비밀 댓글을 볼 때는 올바른 비밀 번호를 입력해야 조회가 가능하다.
>   
>   * 아래와 같이 일반 **비로그인** 사용자가 비밀 댓글을 달고, 관리자가 답글을 비밀 댓글로 다는 경우가 있을 수 있다.
>   * 그럴 때는 최초로 일반 **비로그인** 사용자가 작성한 댓글의 비밀번호를 체크하는 로직을 만들고, 그 로직이 통과가 된다면 답글의 비밀 댓글도 볼 수 있다.
>     ![image](https://user-images.githubusercontent.com/56083021/136324908-d4b4d796-681a-44a3-84e6-64aa1f8712c1.png)
> 
> ## 프론트 구현 사항
> * 댓글 컬럼의 isSecret(이름 변경 가능)이 true면 댓글 관리 페이지의 해당 댓글에 대해 비밀 댓글 표시해 준다.
> * 댓글 컬럼의 isSecret(이름 변경 가능)이 true면 해당 댓글에 대해 비밀 댓글 표시해 준다. (단순히 백엔드에서 댓글의 내용을 "비밀 댓글입니다."라고 하는 것도 좋지만, 추가로 자물쇠 아이콘을 달아주면 더욱 가시성이 좋을 듯하다.)
> * 댓글에 비밀 댓글 체크 박스를 생성한다. (꼭 체크 박스일 필요는 없고, 어떤 방식이든 비밀 댓글 기능 선택이 가능하면 됨.)
> 
> ## 백엔드 구현 사항 가시성 있게 정리
> ================ <응답 모델 변환 시> 비밀 댓글의 작성자가 비로그인 -> 닉네임 노출, 내용 숨김
> 
> 비밀 댓글의 작성자가 로그인 -> 닉네임, 내용 모두 숨김
> 
> ================ <다라쓰 사용자 관점> 사용자가 비로그인 유저 -> 모든 비밀 댓글은 가려져 있고, 비밀 댓글의 비밀 번호를 올바르게 입력해야 내용을 볼 수 있음. -> 로그인 유저의 비밀 댓글을 보기 위한 비밀 번호 입력할 권한 자체가 없음.
> 
> 사용자가 로그인 유저 -> 자기가 쓴 비밀 댓글 외에 모든 비밀 댓글은 가려져 있음. -> 남의 비밀 댓글 보기 위한 비밀 번호 입력할 권한 자체가 없음.
> 
> 사용자가 관리자 -> 모든 댓글 열람 가능.
