### ISSUE TITLE
PR 머지 메세지 컨밴션 관련 

### ISSUE THREAD

**Issue by jujubebat** [woowacourse-teams/2021-darass#99]
아래와 같이 PR 머지 메세지 컨밴션 제안 드립니다. 이슈랑 PR 내역을 같이 볼 수있어서 좋겠다고 생각했어요!

```PR 메세지 (#이슈번호)(#PR번호)```

# 기존
![image](https://user-images.githubusercontent.com/37281119/125613848-7f3f6a60-4fa9-47b1-89a5-bd74c84c8ca8.png)

# 제안 
![image](https://user-images.githubusercontent.com/37281119/125613868-b3fc437b-5e16-4116-8380-ee4b23da7be8.png)
![image](https://user-images.githubusercontent.com/37281119/125613896-93d9a617-b104-4117-b5d0-268ddd29ddbd.png)

**Comment by zereight** [comment]
좋은 아이디어 있으면 바로바로 제안하는 우기 멋있다 👍

**Comment by jaeseongDev** [comment]
좋다고 생각합니다! 바로 도입해도 좋을 것 같네요:)
